services:
  db:
    image: postgres:18
    container_name: bangudb
    restart: always
    environment:
      POSTGRES_DB: bangushopping
      POSTGRES_USER: ctfuser
      POSTGRES_PASSWORD: ctfpass
    volumes:
      - ./db/database.sql:/docker-entrypoint-initdb.d/database.sql:ro
      - postgres_data:/var/lib/postgresql  # <-- aqui é só /var/lib/postgresql
    ports:
      - "5432:5432"

  app:
    build: ./app
    container_name: banguapp
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  postgres_data: